name: Event Management System CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Install dependencies and build the application
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Step 4: Run unit tests
      - name: Run Tests
        run: mvn test

      # Step 5: Archive test results for review
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/

      # Optional Step: Upload built artifacts (e.g., WAR/JAR files)
      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar

  deploy:

    # Deployment stage (Optional, if you have a deployment environment configured)
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        run: |
          echo "Deploying to server..."
          # Add your deployment script here, e.g., SCP or SSH commands
